name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Build out the Drupal infrastructure
      run: |
        git clone --branch main https://github.com/djsutter/bitnami-docker.git docker
        make build
        make docker_build

    - name: Run tests
      run: |
#        make up
#        sleep 5
        make test

    - name: Run installation
      run: |
        make drupal_install
        make drupal_migrate
